export const NAV_LINKS = [
  { label: "Home", href: "/" },
  { label: "Menu", href: "#menu" },
  { label: "About", href: "#about" },
  { label: "Gallery", href: "#gallery" },
  { label: "Offers", href: "#offers" },
  { label: "Contact", href: "#contact" },
];

export const RESTAURANT_INFO = {
  name: "KASIKA",
  nameJa: "カシカ",
  tagline: "Authentic Indian & Asian Dining Experience",
  description:
    "A premium culinary journey through the vibrant flavors of India and Asia, nestled in the heart of Tokorozawa.",
  address: "〒359-1111 埼玉県所沢市緑町4-15-20",
  addressEn: "4-15-20 Midoricho, Tokorozawa, Saitama 359-1111",
  phone: "04-2937-4758",
  mobile: "080-9815-8919",
  owner: "DEVI LAL",
  hours: {
    lunch: "11:30 – 15:00 (L.O. 14:30)",
    dinner: "17:30 – 22:30 (L.O. 22:00)",
    closed: "Tuesday",
  },
  takeout: {
    hours: "11:00am – 22:30pm",
  },
  social: {
    instagram: "#",
    facebook: "#",
    twitter: "#",
  },
};

export const MENU_CATEGORIES = [
  "Starters",
  "Curry",
  "Biryani",
  "Rice & Asian",
  "Set Meals",
  "Soft Drinks",
  "Beer & Sour",
  "Cocktails & Spirits",
];

export interface MenuItem {
  id: number;
  name: string;
  nameJa?: string;
  description: string;
  price: string;
  category: string;
  spice: 0 | 1 | 2 | 3;
  isVeg: boolean;
  isSignature?: boolean;
  image: string;
}

export const MENU_ITEMS: MenuItem[] = [
  // ─── STARTERS ────────────────────────────────────────────────────────────────
  {
    id: 1,
    name: "Tandoori Chicken",
    nameJa: "タンドリーチキン",
    description: "Bone-in chicken marinated overnight in spices, roasted in clay oven. 2 pieces.",
    price: "¥600",
    category: "Starters",
    spice: 2,
    isVeg: false,
    isSignature: true,
    image: "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=600&h=400&fit=crop",
  },
  {
    id: 2,
    name: "Chicken Tikka",
    nameJa: "チキンティッカ",
    description: "Tender boneless chicken marinated in yogurt and spices, grilled in tandoor. 2 pieces.",
    price: "¥390",
    category: "Starters",
    spice: 2,
    isVeg: false,
    isSignature: true,
    image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600&h=400&fit=crop",
  },
  {
    id: 3,
    name: "Sheek Kebab",
    nameJa: "シークケバブ",
    description: "Spiced minced meat skewers grilled in tandoor. 3 pieces.",
    price: "¥650",
    category: "Starters",
    spice: 2,
    isVeg: false,
    image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600&h=400&fit=crop",
  },
  {
    id: 4,
    name: "Malai Tikka",
    nameJa: "マライティッカ",
    description: "Creamy marinated chicken grilled in tandoor. 2 pieces.",
    price: "¥250",
    category: "Starters",
    spice: 1,
    isVeg: false,
    image: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=600&h=400&fit=crop",
  },
  {
    id: 5,
    name: "Fried Chicken",
    nameJa: "フライドチキン",
    description: "Crispy Japanese-style fried chicken. 3 pieces.",
    price: "¥750",
    category: "Starters",
    spice: 1,
    isVeg: false,
    image: "https://images.unsplash.com/photo-1626082927389-6cd097cdc3ec?w=600&h=400&fit=crop",
  },

  // ─── CURRY ───────────────────────────────────────────────────────────────────
  {
    id: 10,
    name: "Mix Vegetable Curry",
    nameJa: "ミックス野菜カレー",
    description: "Seasonal mixed vegetables in a rich aromatic curry sauce.",
    price: "¥700",
    category: "Curry",
    spice: 1,
    isVeg: true,
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&h=400&fit=crop",
  },
  {
    id: 11,
    name: "Mix Dal Curry",
    nameJa: "ミックスダルカレー",
    description: "Mixed lentils slow-cooked with warming spices.",
    price: "¥700",
    category: "Curry",
    spice: 1,
    isVeg: true,
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600&h=400&fit=crop",
  },
  {
    id: 12,
    name: "Chicken Curry",
    nameJa: "チキンカレー",
    description: "Tender chicken in a fragrant tomato-onion curry gravy.",
    price: "¥780",
    category: "Curry",
    spice: 2,
    isVeg: false,
    image: "https://images.unsplash.com/photo-1627662239709-ef777065e49e?w=600&h=400&fit=crop",
  },
  {
    id: 13,
    name: "Keema Curry",
    nameJa: "キーマカレー",
    description: "Spiced minced meat curry cooked with peas and fresh herbs.",
    price: "¥780",
    category: "Curry",
    spice: 2,
    isVeg: false,
    image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600&h=400&fit=crop",
  },
  {
    id: 14,
    name: "Sag Chicken",
    nameJa: "ほうれん草チキン",
    description: "Chicken in a silky smooth spinach and spice sauce.",
    price: "¥880",
    category: "Curry",
    spice: 1,
    isVeg: false,
    isSignature: true,
    image: "https://images.unsplash.com/photo-1585238341710-4abb7692fc0b?w=600&h=400&fit=crop",
  },
  {
    id: 15,
    name: "Mutton Curry",
    nameJa: "マトンカレー",
    description: "Tender mutton braised in bold Indian spices.",
    price: "¥890",
    category: "Curry",
    spice: 3,
    isVeg: false,
    image: "https://images.unsplash.com/photo-1626082927389-6cd097cdc3ec?w=600&h=400&fit=crop",
  },
  {
    id: 16,
    name: "Pork Curry",
    nameJa: "ポークカレー",
    description: "Juicy pork pieces in a rich spiced curry sauce.",
    price: "¥880",
    category: "Curry",
    spice: 2,
    isVeg: false,
    image: "https://images.unsplash.com/photo-1626082927389-6cd097cdc3ec?w=600&h=400&fit=crop",
  },
  {
    id: 17,
    name: "Seafood Curry",
    nameJa: "シーフードカレー",
    description: "Fresh seafood in a coastal-spiced curry gravy.",
    price: "¥880",
    category: "Curry",
    spice: 2,
    isVeg: false,
    image: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=600&h=400&fit=crop",
  },
  {
    id: 18,
    name: "Today's Curry",
    nameJa: "日替わりカレー",
    description: "Chef's daily special curry — ask your server for today's selection.",
    price: "¥880",
    category: "Curry",
    spice: 2,
    isVeg: false,
    image: "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=600&h=400&fit=crop",
  },

  // ─── BIRYANI ─────────────────────────────────────────────────────────────────
  {
    id: 20,
    name: "Chicken Biryani",
    nameJa: "チキンビリヤニ",
    description: "Fragrant basmati rice layered with chicken, onions, and aromatic spices.",
    price: "¥900",
    category: "Biryani",
    spice: 2,
    isVeg: false,
    isSignature: true,
    image: "https://images.unsplash.com/photo-1589985643960-6fe2d67ec22f?w=600&h=400&fit=crop",
  },
  {
    id: 21,
    name: "Pork Biryani",
    nameJa: "ポークビリヤニ",
    description: "Basmati rice slow-cooked with tender pork and whole spices.",
    price: "¥950",
    category: "Biryani",
    spice: 2,
    isVeg: false,
    image: "https://images.unsplash.com/photo-1589985643960-6fe2d67ec22f?w=600&h=400&fit=crop",
  },
  {
    id: 22,
    name: "Mutton Biryani",
    nameJa: "マトンビリヤニ",
    description: "Premium mutton dum-cooked with aged basmati and aromatic herbs.",
    price: "¥950",
    category: "Biryani",
    spice: 2,
    isVeg: false,
    image: "https://images.unsplash.com/photo-1596797038530-2c107229654b?w=600&h=400&fit=crop",
  },
  {
    id: 23,
    name: "Ebi Biryani",
    nameJa: "エビビリヤニ",
    description: "Basmati rice cooked with succulent prawns and coastal spices.",
    price: "¥950",
    category: "Biryani",
    spice: 2,
    isVeg: false,
    image: "https://images.unsplash.com/photo-1596797038530-2c107229654b?w=600&h=400&fit=crop",
  },

  // ─── RICE & ASIAN ─────────────────────────────────────────────────────────────
  {
    id: 30,
    name: "Chicken Chahan",
    nameJa: "チキンチャーハン",
    description: "Japanese-style fried rice with seasoned chicken.",
    price: "¥600",
    category: "Rice & Asian",
    spice: 0,
    isVeg: false,
    image: "https://images.unsplash.com/photo-1609501676725-7186f017a4b0?w=600&h=400&fit=crop",
  },
  {
    id: 31,
    name: "Ebi Chahan",
    nameJa: "海老チャーハン",
    description: "Fragrant fried rice with fresh prawns.",
    price: "¥700",
    category: "Rice & Asian",
    spice: 0,
    isVeg: false,
    isSignature: true,
    image: "https://images.unsplash.com/photo-1596797038530-2c107229654b?w=600&h=400&fit=crop",
  },
  {
    id: 32,
    name: "Pork Chahan",
    nameJa: "ポークチャーハン",
    description: "Fried rice with tender pork pieces.",
    price: "¥650",
    category: "Rice & Asian",
    spice: 0,
    isVeg: false,
    image: "https://images.unsplash.com/photo-1609501676725-7186f017a4b0?w=600&h=400&fit=crop",
  },
  {
    id: 33,
    name: "Egg Chahan",
    nameJa: "卵チャーハン",
    description: "Classic fried rice with egg.",
    price: "¥550",
    category: "Rice & Asian",
    spice: 0,
    isVeg: true,
    image: "https://images.unsplash.com/photo-1609501676725-7186f017a4b0?w=600&h=400&fit=crop",
  },
  {
    id: 34,
    name: "Vegetable Chahan",
    nameJa: "野菜チャーハン",
    description: "Fried rice with seasonal vegetables.",
    price: "¥550",
    category: "Rice & Asian",
    spice: 0,
    isVeg: true,
    image: "https://images.unsplash.com/photo-1609501676725-7186f017a4b0?w=600&h=400&fit=crop",
  },
  {
    id: 35,
    name: "Kasika Special Pork Don",
    nameJa: "カシカスペシャル豚丼セット",
    description: "Thai-style sweet chili pork over rice. Pork 150g with Rice 250g.",
    price: "¥850",
    category: "Rice & Asian",
    spice: 1,
    isVeg: false,
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&h=400&fit=crop",
  },
  {
    id: 36,
    name: "Kasika Special Chicken Don",
    nameJa: "カシカスペシャルチキン丼セット",
    description: "Thai-style sweet chili chicken over rice with boiled egg. Chicken 150g with Rice 250g.",
    price: "¥850",
    category: "Rice & Asian",
    spice: 1,
    isVeg: false,
    isSignature: true,
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&h=400&fit=crop",
  },
  {
    id: 37,
    name: "Kasika Special Sausage Don",
    nameJa: "カシカスペシャルソーセージ丼セット",
    description: "Thai-style sweet chili sausage over rice. Sausage 150g with Rice 250g.",
    price: "¥850",
    category: "Rice & Asian",
    spice: 1,
    isVeg: false,
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&h=400&fit=crop",
  },
  {
    id: 38,
    name: "Kasika Special Ebi Don",
    nameJa: "カシカスペシャルエビ丼セット",
    description: "Thai-style sweet chili prawns over rice. Shrimp 7P with Rice 250g.",
    price: "¥900",
    category: "Rice & Asian",
    spice: 1,
    isVeg: false,
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&h=400&fit=crop",
  },
  {
    id: 39,
    name: "Kasika Special Gapao Set",
    nameJa: "カシカスペシャルガパオセット",
    description: "Thai basil minced meat (chicken or pork) with fried egg over rice. 150g with Rice 250g.",
    price: "¥850",
    category: "Rice & Asian",
    spice: 2,
    isVeg: false,
    isSignature: true,
    image: "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=600&h=400&fit=crop",
  },

  // ─── SET MEALS ────────────────────────────────────────────────────────────────
  {
    id: 50,
    name: "Single Curry Set",
    nameJa: "シングルカレーセット",
    description: "One choice curry (from 9 options) with Salad, Nan or Rice, Soft Drink.",
    price: "¥700~",
    category: "Set Meals",
    spice: 1,
    isVeg: false,
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&h=400&fit=crop",
  },
  {
    id: 51,
    name: "Butter Chicken Set",
    nameJa: "バターチキンセット",
    description: "Butter Chicken Curry with Salad, Nan or Rice, Soft Drink.",
    price: "¥950",
    category: "Set Meals",
    spice: 1,
    isVeg: false,
    isSignature: true,
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&h=400&fit=crop",
  },
  {
    id: 52,
    name: "Ladies Set",
    nameJa: "レディースセット",
    description: "Two choice curry with Salad, Chicken Tikka, Nan or Rice, Soft Drink.",
    price: "¥980",
    category: "Set Meals",
    spice: 1,
    isVeg: false,
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&h=400&fit=crop",
  },
  {
    id: 53,
    name: "Tandoori Set",
    nameJa: "タンドリーセット",
    description: "Two choice curry with Salad, Tandoori Chicken, Nan or Rice, Soft Drink.",
    price: "¥1,100",
    category: "Set Meals",
    spice: 2,
    isVeg: false,
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&h=400&fit=crop",
  },
  {
    id: 54,
    name: "Cheese Nan Set",
    nameJa: "チーズナンセット",
    description: "One choice curry with Salad, Cheese Nan, Soft Drink.",
    price: "¥1,050",
    category: "Set Meals",
    spice: 1,
    isVeg: false,
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&h=400&fit=crop",
  },
  {
    id: 55,
    name: "Gapao Rice Set",
    nameJa: "ガパオライスセット",
    description: "Thai basil minced meat fried rice with Salad, Soft Drink.",
    price: "¥850",
    category: "Set Meals",
    spice: 2,
    isVeg: false,
    image: "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=600&h=400&fit=crop",
  },
  {
    id: 56,
    name: "Beer Set",
    nameJa: "ビールセット",
    description: "Butter Chicken Curry with Salad, Chicken Tikka, Sheek Kebab, Nan or Rice, Draft Beer.",
    price: "¥1,400",
    category: "Set Meals",
    spice: 1,
    isVeg: false,
    isSignature: true,
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&h=400&fit=crop",
  },
  {
    id: 57,
    name: "Student Set",
    nameJa: "学生セット",
    description: "One choice curry (1–9) with Salad, Nan or Rice, Soft Drink.",
    price: "¥650",
    category: "Set Meals",
    spice: 1,
    isVeg: false,
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&h=400&fit=crop",
  },
  {
    id: 58,
    name: "Baby Set",
    nameJa: "お子様セット",
    description: "One mild curry (Butter Chicken / Chicken / Keema) with Salad, Nan or Rice, Soft Drink.",
    price: "¥550",
    category: "Set Meals",
    spice: 0,
    isVeg: false,
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&h=400&fit=crop",
  },
  {
    id: 59,
    name: "A Bento (Takeout)",
    nameJa: "A弁当",
    description: "One choice curry (1–9) with Nan or Rice. Takeout available 11:00–22:00.",
    price: "¥600",
    category: "Set Meals",
    spice: 1,
    isVeg: false,
    image: "https://images.unsplash.com/photo-1574484284002-952d92456975?w=600&q=80",
  },
  {
    id: 60,
    name: "B Bento (Takeout)",
    nameJa: "B弁当",
    description: "One choice curry (1–9) with Nan, Rice, Salad, Chicken 1P. Takeout 11:00–22:00.",
    price: "¥750",
    category: "Set Meals",
    spice: 1,
    isVeg: false,
    image: "https://images.unsplash.com/photo-1574484284002-952d92456975?w=600&q=80",
  },
  {
    id: 61,
    name: "Cheese Nan Bento (Takeout)",
    nameJa: "チーズナン弁当",
    description: "One choice curry (1–9) with Cheese Nan. Takeout available 11:00–22:00.",
    price: "¥1,000",
    category: "Set Meals",
    spice: 1,
    isVeg: false,
    image: "https://images.unsplash.com/photo-1574484284002-952d92456975?w=600&q=80",
  },
  {
    id: 62,
    name: "C Bento (Takeout)",
    nameJa: "C弁当",
    description: "Choose from premium curries: Butter Chicken, Mutton Masala, Chicken Masala, Gapao Rice, Prawn Curry, Prawn Butter Masala, or Spinach Mutton. With Nan or Rice.",
    price: "¥850",
    category: "Set Meals",
    spice: 2,
    isVeg: false,
    isSignature: true,
    image: "https://images.unsplash.com/photo-1574484284002-952d92456975?w=600&q=80",
  },
  {
    id: 63,
    name: "Stir-Fried Pork Set (Takeout)",
    nameJa: "豚炒め＋ライス＋サラダ",
    description: "Stir-fried pork with Rice and Salad. Takeout available 11:00–22:00.",
    price: "¥850",
    category: "Set Meals",
    spice: 1,
    isVeg: false,
    image: "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=600&q=80",
  },

  // ─── SOFT DRINKS ─────────────────────────────────────────────────────────────
  {
    id: 70,
    name: "Lassi",
    nameJa: "ラッシー",
    description: "Classic chilled yogurt drink.",
    price: "¥300",
    category: "Soft Drinks",
    spice: 0,
    isVeg: true,
    image: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600&h=400&fit=crop",
  },
  {
    id: 71,
    name: "Mango Lassi",
    nameJa: "マンゴーラッシー",
    description: "Chilled yogurt blended with ripe mango.",
    price: "¥350",
    category: "Soft Drinks",
    spice: 0,
    isVeg: true,
    isSignature: true,
    image: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600&h=400&fit=crop",
  },
  {
    id: 72,
    name: "Strawberry Lassi",
    nameJa: "いちごラッシー",
    description: "Creamy yogurt blended with strawberry.",
    price: "¥400",
    category: "Soft Drinks",
    spice: 0,
    isVeg: true,
    image: "https://images.unsplash.com/photo-1533134242443-742ce60857f9?w=600&h=400&fit=crop",
  },
  {
    id: 73,
    name: "Blueberry Lassi",
    nameJa: "ブルーベリーラッシー",
    description: "Creamy yogurt blended with blueberry.",
    price: "¥400",
    category: "Soft Drinks",
    spice: 0,
    isVeg: true,
    image: "https://images.unsplash.com/photo-1553530666-ba2a8e36c8fe?w=600&h=400&fit=crop",
  },
  {
    id: 74,
    name: "Banana Lassi",
    nameJa: "バナナラッシー",
    description: "Creamy yogurt blended with banana.",
    price: "¥400",
    category: "Soft Drinks",
    spice: 0,
    isVeg: true,
    image: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600&h=400&fit=crop",
  },
  {
    id: 75,
    name: "Peach Lassi",
    nameJa: "ピーチラッシー",
    description: "Creamy yogurt blended with peach.",
    price: "¥400",
    category: "Soft Drinks",
    spice: 0,
    isVeg: true,
    image: "https://images.unsplash.com/photo-1533134242443-742ce60857f9?w=600&h=400&fit=crop",
  },
  {
    id: 76,
    name: "Cola",
    nameJa: "コーラ",
    description: "Chilled cola.",
    price: "¥300",
    category: "Soft Drinks",
    spice: 0,
    isVeg: true,
    image: "https://images.unsplash.com/photo-1554866585-575d7ea2fbf7?w=600&h=400&fit=crop",
  },
  {
    id: 77,
    name: "Oolong Tea",
    nameJa: "ウーロン茶",
    description: "Chilled oolong tea.",
    price: "¥300",
    category: "Soft Drinks",
    spice: 0,
    isVeg: true,
    image: "https://images.unsplash.com/photo-1597318373768-47a9fbf69aeb?w=600&h=400&fit=crop",
  },
  {
    id: 78,
    name: "Green Tea",
    nameJa: "緑茶",
    description: "Chilled or hot green tea.",
    price: "¥300",
    category: "Soft Drinks",
    spice: 0,
    isVeg: true,
    image: "https://images.unsplash.com/photo-1597318373768-47a9fbf69aeb?w=600&h=400&fit=crop",
  },
  {
    id: 79,
    name: "Masala Tea",
    nameJa: "マサラティー",
    description: "Spiced Indian tea with ginger and cardamom. ICE or HOT.",
    price: "¥300",
    category: "Soft Drinks",
    spice: 1,
    isVeg: true,
    image: "https://images.unsplash.com/photo-1544432415-c0a63c35d31f?w=600&h=400&fit=crop",
  },
  {
    id: 80,
    name: "Coffee",
    nameJa: "コーヒー",
    description: "Coffee served ICE or HOT.",
    price: "¥300",
    category: "Soft Drinks",
    spice: 0,
    isVeg: true,
    image: "https://images.unsplash.com/photo-1495521826927-30cbf565b904?w=600&h=400&fit=crop",
  },
  {
    id: 81,
    name: "Orange Juice",
    nameJa: "オレンジジュース",
    description: "Fresh orange juice.",
    price: "¥300",
    category: "Soft Drinks",
    spice: 0,
    isVeg: true,
    image: "https://images.unsplash.com/photo-1600271886742-f049cd1f5103?w=600&h=400&fit=crop",
  },
  {
    id: 82,
    name: "Peach Soda",
    nameJa: "ピーチソーダ",
    description: "Refreshing peach-flavoured soda.",
    price: "¥300",
    category: "Soft Drinks",
    spice: 0,
    isVeg: true,
    image: "https://images.unsplash.com/photo-1554866585-575d7ea2fbf7?w=600&h=400&fit=crop",
  },
  {
    id: 83,
    name: "Ginger Ale",
    nameJa: "ジンジャーエール",
    description: "Chilled ginger ale.",
    price: "¥300",
    category: "Soft Drinks",
    spice: 0,
    isVeg: true,
    image: "https://images.unsplash.com/photo-1554866585-575d7ea2fbf7?w=600&h=400&fit=crop",
  },

  // ─── BEER & SOUR ─────────────────────────────────────────────────────────────
  {
    id: 90,
    name: "Asahi Draft Beer",
    nameJa: "アサヒ生ビール",
    description: "Cold fresh Asahi draft beer.",
    price: "¥450",
    category: "Beer & Sour",
    spice: 0,
    isVeg: true,
    isSignature: true,
    image: "https://images.unsplash.com/photo-1618183479302-1461ae109846?w=600&h=400&fit=crop",
  },
  {
    id: 91,
    name: "Asahi Bottle Beer",
    nameJa: "アサヒ瓶ビール",
    description: "Asahi bottled beer.",
    price: "¥500",
    category: "Beer & Sour",
    spice: 0,
    isVeg: true,
    image: "https://images.unsplash.com/photo-1618183479302-1461ae109846?w=600&h=400&fit=crop",
  },
  {
    id: 92,
    name: "Sapporo Bottle Beer",
    nameJa: "サッポロ瓶ビール",
    description: "Sapporo bottled beer.",
    price: "¥500",
    category: "Beer & Sour",
    spice: 0,
    isVeg: true,
    image: "https://images.unsplash.com/photo-1618183479302-1461ae109846?w=600&h=400&fit=crop",
  },
  {
    id: 93,
    name: "Kirin Bottle Beer",
    nameJa: "キリン瓶ビール",
    description: "Kirin bottled beer.",
    price: "¥500",
    category: "Beer & Sour",
    spice: 0,
    isVeg: true,
    image: "https://images.unsplash.com/photo-1618183479302-1461ae109846?w=600&h=400&fit=crop",
  },
  {
    id: 94,
    name: "Heineken",
    nameJa: "ハイネケン",
    description: "Premium Dutch lager.",
    price: "¥500",
    category: "Beer & Sour",
    spice: 0,
    isVeg: true,
    image: "https://images.unsplash.com/photo-1608270861620-7a8e3e10b574?w=600&h=400&fit=crop",
  },
  {
    id: 95,
    name: "Corona Beer",
    nameJa: "コロナビール",
    description: "Mexican lager, refreshing and light.",
    price: "¥500",
    category: "Beer & Sour",
    spice: 0,
    isVeg: true,
    image: "https://images.unsplash.com/photo-1608270861620-7a8e3e10b574?w=600&h=400&fit=crop",
  },
  {
    id: 96,
    name: "Nepal Beer",
    nameJa: "ネパールビール",
    description: "Imported Nepali lager.",
    price: "¥500",
    category: "Beer & Sour",
    spice: 0,
    isVeg: true,
    image: "https://images.unsplash.com/photo-1618183479302-1461ae109846?w=600&h=400&fit=crop",
  },
  {
    id: 97,
    name: "India Beer",
    nameJa: "インドビール",
    description: "Imported Indian lager.",
    price: "¥500",
    category: "Beer & Sour",
    spice: 0,
    isVeg: true,
    image: "https://images.unsplash.com/photo-1618183479302-1461ae109846?w=600&h=400&fit=crop",
  },
  {
    id: 98,
    name: "Kasika Beer",
    nameJa: "カシカビール",
    description: "KASIKA's house craft beer.",
    price: "¥450",
    category: "Beer & Sour",
    spice: 0,
    isVeg: true,
    isSignature: true,
    image: "https://images.unsplash.com/photo-1618183479302-1461ae109846?w=600&h=400&fit=crop",
  },
  {
    id: 99,
    name: "Mango Beer",
    nameJa: "マンゴービール",
    description: "Refreshing mango-flavoured beer.",
    price: "¥450",
    category: "Beer & Sour",
    spice: 0,
    isVeg: true,
    image: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600&h=400&fit=crop",
  },
  {
    id: 100,
    name: "Non-Alcoholic Beer",
    nameJa: "ノンアルコール",
    description: "Alcohol-free beer option.",
    price: "¥350",
    category: "Beer & Sour",
    spice: 0,
    isVeg: true,
    image: "https://images.unsplash.com/photo-1618183479302-1461ae109846?w=600&h=400&fit=crop",
  },
  {
    id: 101,
    name: "Kaku Highball",
    nameJa: "角ハイボール",
    description: "Suntory Kaku whisky highball.",
    price: "¥400",
    category: "Beer & Sour",
    spice: 0,
    isVeg: true,
    image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600&h=400&fit=crop",
  },
  {
    id: 102,
    name: "Kasika Special Highball",
    nameJa: "カシカスペシャルハイボール",
    description: "KASIKA's house special whisky highball.",
    price: "¥400",
    category: "Beer & Sour",
    spice: 0,
    isVeg: true,
    isSignature: true,
    image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600&h=400&fit=crop",
  },
  {
    id: 103,
    name: "Dewar's Highball",
    nameJa: "デュワーズハイボール",
    description: "Dewar's Scotch whisky highball.",
    price: "¥400",
    category: "Beer & Sour",
    spice: 0,
    isVeg: true,
    image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600&h=400&fit=crop",
  },
  {
    id: 104,
    name: "Indian Rum Highball",
    nameJa: "インドラムハイボール",
    description: "Indian rum highball.",
    price: "¥450",
    category: "Beer & Sour",
    spice: 0,
    isVeg: true,
    image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600&h=400&fit=crop",
  },
  {
    id: 105,
    name: "Indian Whisky Highball",
    nameJa: "インドウイスキーハイボール",
    description: "Indian whisky highball.",
    price: "¥450",
    category: "Beer & Sour",
    spice: 0,
    isVeg: true,
    image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600&h=400&fit=crop",
  },
  {
    id: 106,
    name: "Black Nikka Highball",
    nameJa: "ブラックニッカハイボール",
    description: "Black Nikka whisky highball.",
    price: "¥350",
    category: "Beer & Sour",
    spice: 0,
    isVeg: true,
    image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600&h=400&fit=crop",
  },
  {
    id: 107,
    name: "Lemon Sour",
    nameJa: "レモンサワー",
    description: "Refreshing lemon sour.",
    price: "¥400",
    category: "Beer & Sour",
    spice: 0,
    isVeg: true,
    image: "https://images.unsplash.com/photo-1583969212155-72933dcb0c91?w=600&h=400&fit=crop",
  },
  {
    id: 108,
    name: "Mango Sour",
    nameJa: "マンゴーサワー",
    description: "Mango-flavoured sour.",
    price: "¥400",
    category: "Beer & Sour",
    spice: 0,
    isVeg: true,
    image: "https://images.unsplash.com/photo-1583969212155-72933dcb0c91?w=600&h=400&fit=crop",
  },
  {
    id: 109,
    name: "Peach Sour",
    nameJa: "ピーチサワー",
    description: "Peach-flavoured sour.",
    price: "¥400",
    category: "Beer & Sour",
    spice: 0,
    isVeg: true,
    image: "https://images.unsplash.com/photo-1583969212155-72933dcb0c91?w=600&h=400&fit=crop",
  },
  {
    id: 110,
    name: "Lassi Sour",
    nameJa: "ラッシーサワー",
    description: "Lassi-style sour cocktail.",
    price: "¥400",
    category: "Beer & Sour",
    spice: 0,
    isVeg: true,
    image: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600&h=400&fit=crop",
  },
  {
    id: 111,
    name: "Tofu Sour",
    nameJa: "豆腐サワー",
    description: "Unique tofu-based sour.",
    price: "¥400",
    category: "Beer & Sour",
    spice: 0,
    isVeg: true,
    image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600&h=400&fit=crop",
  },
  {
    id: 112,
    name: "Oolong Hai",
    nameJa: "ウーロンハイ",
    description: "Oolong tea highball.",
    price: "¥350",
    category: "Beer & Sour",
    spice: 0,
    isVeg: true,
    image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600&h=400&fit=crop",
  },
  {
    id: 113,
    name: "Green Tea Hai",
    nameJa: "緑茶ハイ",
    description: "Green tea highball.",
    price: "¥350",
    category: "Beer & Sour",
    spice: 0,
    isVeg: true,
    image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600&h=400&fit=crop",
  },
  {
    id: 114,
    name: "Hoppy Set",
    nameJa: "ホッピーセット",
    description: "Hoppy beer-like drink set.",
    price: "¥400",
    category: "Beer & Sour",
    spice: 0,
    isVeg: true,
    image: "https://images.unsplash.com/photo-1618183479302-1461ae109846?w=600&h=400&fit=crop",
  },

  // ─── COCKTAILS & SPIRITS ─────────────────────────────────────────────────────
  {
    id: 120,
    name: "Gin Tonic",
    nameJa: "ジントニック",
    description: "Classic gin and tonic cocktail.",
    price: "¥450",
    category: "Cocktails & Spirits",
    spice: 0,
    isVeg: true,
    image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600&h=400&fit=crop",
  },
  {
    id: 121,
    name: "Rum Lassi",
    nameJa: "ラムラッシー",
    description: "Rum blended with creamy lassi.",
    price: "¥500",
    category: "Cocktails & Spirits",
    spice: 0,
    isVeg: true,
    isSignature: true,
    image: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600&h=400&fit=crop",
  },
  {
    id: 122,
    name: "Rum Mango",
    nameJa: "ラムマンゴー",
    description: "Rum cocktail with mango.",
    price: "¥500",
    category: "Cocktails & Spirits",
    spice: 0,
    isVeg: true,
    image: "https://images.unsplash.com/photo-1583969212155-72933dcb0c91?w=600&h=400&fit=crop",
  },
  {
    id: 123,
    name: "Rum Orange",
    nameJa: "ラムオレンジ",
    description: "Rum cocktail with orange.",
    price: "¥500",
    category: "Cocktails & Spirits",
    spice: 0,
    isVeg: true,
    image: "https://images.unsplash.com/photo-1583969212155-72933dcb0c91?w=600&h=400&fit=crop",
  },
  {
    id: 124,
    name: "Rum Coke",
    nameJa: "ラムコーク",
    description: "Classic rum and cola.",
    price: "¥500",
    category: "Cocktails & Spirits",
    spice: 0,
    isVeg: true,
    image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600&h=400&fit=crop",
  },
  {
    id: 125,
    name: "Glass Wine",
    nameJa: "グラスワイン",
    description: "Glass of red or white wine.",
    price: "¥450",
    category: "Cocktails & Spirits",
    spice: 0,
    isVeg: true,
    image: "https://images.unsplash.com/photo-1510812431401-41d2cab2707d?w=600&h=400&fit=crop",
  },
  {
    id: 126,
    name: "Bottle Wine",
    nameJa: "ボトルワイン",
    description: "Bottle of red, white, or rosé wine.",
    price: "¥1,550",
    category: "Cocktails & Spirits",
    spice: 0,
    isVeg: true,
    image: "https://images.unsplash.com/photo-1510812431401-41d2cab2707d?w=600&h=400&fit=crop",
  },
  {
    id: 127,
    name: "Dewar's Whisky",
    nameJa: "デュワーズウイスキー",
    description: "Scotch whisky by the glass or bottle.",
    price: "Glass ¥450 / Bottle ¥2,500",
    category: "Cocktails & Spirits",
    spice: 0,
    isVeg: true,
    image: "https://images.unsplash.com/photo-1608270861620-7a8e3e10b574?w=600&h=400&fit=crop",
  },
  {
    id: 128,
    name: "Indian Whisky",
    nameJa: "インドウイスキー",
    description: "Indian whisky by the glass or bottle.",
    price: "Glass ¥500 / Bottle ¥3,500",
    category: "Cocktails & Spirits",
    spice: 0,
    isVeg: true,
    image: "https://images.unsplash.com/photo-1608270861620-7a8e3e10b574?w=600&h=400&fit=crop",
  },
  {
    id: 129,
    name: "Suntory Kaku",
    nameJa: "サントリー角",
    description: "Suntory Kaku Japanese whisky, glass or bottle.",
    price: "Glass ¥450 / Bottle ¥2,500",
    category: "Cocktails & Spirits",
    spice: 0,
    isVeg: true,
    image: "https://images.unsplash.com/photo-1608270861620-7a8e3e10b574?w=600&h=400&fit=crop",
  },
  {
    id: 130,
    name: "Chivas Regal",
    nameJa: "シーバスリーガル",
    description: "Premium Scotch blended whisky, glass or bottle.",
    price: "Glass ¥500 / Bottle ¥3,500",
    category: "Cocktails & Spirits",
    spice: 0,
    isVeg: true,
    image: "https://images.unsplash.com/photo-1608270861620-7a8e3e10b574?w=600&h=400&fit=crop",
  },
  {
    id: 131,
    name: "Myer's Rum",
    nameJa: "マイヤーズラム",
    description: "Dark Jamaican rum, glass or bottle.",
    price: "Glass ¥500 / Bottle ¥3,500",
    category: "Cocktails & Spirits",
    spice: 0,
    isVeg: true,
    image: "https://images.unsplash.com/photo-1608270861620-7a8e3e10b574?w=600&h=400&fit=crop",
  },
  {
    id: 132,
    name: "McDowell's Whisky",
    nameJa: "マクダウェルウイスキー",
    description: "Indian McDowell's whisky, glass or bottle.",
    price: "Glass ¥500 / Bottle ¥3,500",
    category: "Cocktails & Spirits",
    spice: 0,
    isVeg: true,
    image: "https://images.unsplash.com/photo-1608270861620-7a8e3e10b574?w=600&h=400&fit=crop",
  },
  {
    id: 133,
    name: "McDowell's Rum",
    nameJa: "マクダウェルラム",
    description: "Indian McDowell's rum, glass or bottle.",
    price: "Glass ¥500 / Bottle ¥3,500",
    category: "Cocktails & Spirits",
    spice: 0,
    isVeg: true,
    image: "https://images.unsplash.com/photo-1608270861620-7a8e3e10b574?w=600&h=400&fit=crop",
  },
  {
    id: 134,
    name: "Khukuri Rum",
    nameJa: "ククリラム",
    description: "Nepali Khukuri rum, glass or bottle.",
    price: "Glass ¥500 / Bottle ¥3,500",
    category: "Cocktails & Spirits",
    spice: 0,
    isVeg: true,
    image: "https://images.unsplash.com/photo-1608270861620-7a8e3e10b574?w=600&h=400&fit=crop",
  },
  {
    id: 135,
    name: "Kara-imo Shochu",
    nameJa: "から芋焼酎",
    description: "Sweet potato shochu, glass or bottle.",
    price: "Glass ¥400 / Bottle ¥2,500",
    category: "Cocktails & Spirits",
    spice: 0,
    isVeg: true,
    image: "https://images.unsplash.com/photo-1608270861620-7a8e3e10b574?w=600&h=400&fit=crop",
  },
  {
    id: 136,
    name: "Warasaki Shochu",
    nameJa: "和ら咲焼酎",
    description: "Japanese shochu, glass or bottle.",
    price: "Glass ¥400 / Bottle ¥2,500",
    category: "Cocktails & Spirits",
    spice: 0,
    isVeg: true,
    image: "https://images.unsplash.com/photo-1608270861620-7a8e3e10b574?w=600&h=400&fit=crop",
  },
  {
    id: 137,
    name: "Jinro Shochu",
    nameJa: "ジンロ",
    description: "Korean Jinro soju/shochu, glass or bottle.",
    price: "Glass ¥350 / Bottle ¥2,500",
    category: "Cocktails & Spirits",
    spice: 0,
    isVeg: true,
    image: "https://images.unsplash.com/photo-1608270861620-7a8e3e10b574?w=600&h=400&fit=crop",
  },
  {
    id: 138,
    name: "Ichigo Shochu",
    nameJa: "いちご焼酎",
    description: "Strawberry shochu, glass or bottle.",
    price: "Glass ¥400 / Bottle ¥2,500",
    category: "Cocktails & Spirits",
    spice: 0,
    isVeg: true,
    image: "https://images.unsplash.com/photo-1533134242443-742ce60857f9?w=600&h=400&fit=crop",
  },
];

// ─── PARTY MENU COURSES ───────────────────────────────────────────────────────
export interface PartyCourse {
  label: string;
  labelJa: string;
  price: string;
  duration: string;
  items: string[];
  drinkNote?: string;
  isPopular?: boolean;
}

export const PARTY_COURSES: PartyCourse[] = [
  {
    label: "A Course",
    labelJa: "Aコース",
    price: "¥2,000",
    duration: "2 hours",
    items: [
      "Papad",
      "Green Salad",
      "One choice curry",
      "Freshly baked Nan",
      "Soft Drink",
    ],
  },
  {
    label: "B Course",
    labelJa: "Bコース",
    price: "¥3,500",
    duration: "2 hours",
    isPopular: true,
    items: [
      "Papad",
      "Green Salad",
      "Beans Salad",
      "Deep Fried Chicken",
      "Tandoori Chicken",
      "Sheek Kebab",
      "Edamame",
      "One choice curry",
      "Freshly baked Nan",
      "Soft Drink / Alcohol",
    ],
    drinkNote: "All-you-can-drink included (except Khukuri Rum, Nepal Beer & India Beer)",
  },
  {
    label: "C Course",
    labelJa: "Cコース",
    price: "¥4,000",
    duration: "2.5 hours",
    items: [
      "Papad",
      "Green Salad",
      "Beans Salad",
      "Deep Fried Chicken",
      "Tandoori Chicken",
      "Sheek Kebab",
      "Edamame",
      "One choice curry",
      "Freshly baked Nan",
      "Soft Drink / Alcohol",
    ],
    drinkNote: "All-you-can-drink included (except Khukuri Rum, Nepal Beer & India Beer)",
  },
];

// ─── CATEGORIES FEATURED ─────────────────────────────────────────────────────
export const CATEGORIES_FEATURED = [
  {
    title: "Indian Curry",
    titleJa: "インドカレー",
    description: "9 varieties from ¥700 — Vegetable, Dal, Chicken, Keema, Sag, Mutton, Pork, Seafood & Today's",
    image: "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=800&q=80",
    count: "9 curries",
  },
  {
    title: "Tandoori Starters",
    titleJa: "タンドーリ",
    description: "Clay-oven Tandoori Chicken, Chicken Tikka, Malai Tikka, Sheek Kebab & Fried Chicken",
    image: "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=800&q=80",
    count: "5 dishes",
  },
  {
    title: "Biryani",
    titleJa: "ビリヤニ",
    description: "Fragrant basmati rice with Chicken ¥900, Pork ¥950, Mutton ¥950 or Prawn ¥950",
    image: "https://images.unsplash.com/photo-1563379091339-03246963d60e?w=800&q=80",
    count: "4 dishes",
  },
  {
    title: "Asian Dishes",
    titleJa: "アジア料理",
    description: "Kasika Thai Don plates, Gapao Sets, Chahan fried rice — Japanese and Thai favourites",
    image: "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800&q=80",
    count: "10 dishes",
  },
  {
    title: "Drinks & Bar",
    titleJa: "ドリンク・バー",
    description: "Lassi in 6 flavours, craft beers, highballs, cocktails, wine, shochu and spirits",
    image: "https://images.unsplash.com/photo-1546173159-315724a31696?w=800&q=80",
    count: "40+ drinks",
  },
  {
    title: "Set Meals",
    titleJa: "セットメニュー",
    description: "Single Curry Set ¥700~, Butter Chicken Set ¥950, Beer Set ¥1,400 and 10 more sets",
    image: "https://images.unsplash.com/photo-1574484284002-952d92456975?w=800&q=80",
    count: "13 sets",
  },
];

// ─── TESTIMONIALS ─────────────────────────────────────────────────────────────
export const TESTIMONIALS = [
  {
    id: 1,
    name: "Yamamoto Keiko",
    location: "Tokorozawa, Saitama",
    rating: 5,
    review:
      "Absolutely stunning food and atmosphere. The Butter Chicken Set is the best I've had outside of India. KASIKA has become our family's favourite — we visit every month without fail.",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&q=80",
  },
  {
    id: 2,
    name: "Tanaka Hiroshi",
    location: "Tokorozawa, Saitama",
    rating: 5,
    review:
      "The Mutton Biryani is extraordinary — perfectly fragrant rice, tender meat, and that beautiful golden colour. The ambiance is elegant and the staff incredibly welcoming.",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80",
  },
  {
    id: 3,
    name: "Sato Miyuki",
    location: "Tokyo",
    rating: 5,
    review:
      "Worth the trip from Tokyo! The Party Course B was perfect for our group dinner. Chicken Tikka and Mango Lassi together were absolutely divine.",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=80",
  },
  {
    id: 4,
    name: "Nakamura Ryo",
    location: "Hanno, Saitama",
    rating: 5,
    review:
      "The chef clearly has mastered Indian and Asian cuisine. Every dish is balanced with care and presented beautifully. KASIKA is a hidden gem in Saitama.",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&q=80",
  },
];

// ─── GALLERY IMAGES ───────────────────────────────────────────────────────────
export const GALLERY_IMAGES = [
  {
    src: "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=600&q=80",
    alt: "Indian Curry",
    aspect: "tall",
  },
  {
    src: "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=600&q=80",
    alt: "Tandoori Chicken",
    aspect: "wide",
  },
  {
    src: "https://images.unsplash.com/photo-1563379091339-03246963d60e?w=600&q=80",
    alt: "Chicken Biryani",
    aspect: "tall",
  },
  {
    src: "https://images.unsplash.com/photo-1574484284002-952d92456975?w=600&q=80",
    alt: "Curry Set Meal",
    aspect: "short",
  },
  {
    src: "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=600&q=80",
    alt: "Asian Dishes",
    aspect: "tall",
  },
  {
    src: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=600&q=80",
    alt: "Starters Platter",
    aspect: "short",
  },
  {
    src: "https://images.unsplash.com/photo-1546173159-315724a31696?w=600&q=80",
    alt: "Mango Lassi",
    aspect: "tall",
  },
  {
    src: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600&q=80",
    alt: "Chicken Tikka",
    aspect: "wide",
  },
  {
    src: "https://images.unsplash.com/photo-1596797038530-2c107229654b?w=600&q=80",
    alt: "Biryani Spread",
    aspect: "short",
  },
  {
    src: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600&q=80",
    alt: "Dal Curry",
    aspect: "tall",
  },
  {
    src: "https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=600&q=80",
    alt: "Bar & Drinks",
    aspect: "short",
  },
  {
    src: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=600&q=80",
    alt: "Set Meal Spread",
    aspect: "wide",
  },
];
